export const labCopy = {
  en: {
    home: "UI Style Lab home",
    tagline: "Design the layers. See the whole page.",
    pageNav: "Page navigation",
    introKicker: "INTERACTIVE UI REFERENCE",
    title: ["Mix design languages.", "See the whole system."],
    intro: "Choose eight coordinated layers and watch the same interface transform instantly—from typography and charts to navigation and page rhythm.",
    introOnly: "Choose eight coordinated layers and watch the same interface transform instantly—from typography and charts to navigation and page rhythm.",
    explore: "View live canvas",
    agentGuideKicker: "AGENT-ASSISTED REVIEW",
    agentGuideTitle: "Let an agent explore the lab.",
    agentGuideBody: "Share the Agent Guide so it can inspect compatible combinations, open reference canvases, and compare their evidence directly—no installation required.",
    agentGuideLink: "Open Agent Guide",
    count: "validated combinations",
    mixer: "Design combination mixer",
    random: "Create a random compatible combination",
    share: "Share the current combination",
    undo: "Undo the last combination change",
    redo: "Redo the last combination change",
    randomShort: "Random",
    shareShort: "Share",
    undoShort: "Undo",
    redoShort: "Redo",
    presetsJump: "Presets",
    presetsJumpLabel: "Jump to curated presets",
    canvasJump: "Canvas",
    canvasJumpLabel: "Return to the live canvas",
    shareTitle: "Choose a share view",
    shareIntro: "Send the full lab for exploration or a clean reference page for agents and design handoff.",
    labLink: "Copy lab link",
    labLinkNote: "Mixer, presets, and the selected canvas",
    referenceLink: "Copy reference view",
    referenceLinkNote: "The selected live canvas only · agent-ready",
    languageMenu: "Language and content mode",
    englishMode: "English",
    koreanOnlyMode: "한국어 only",
    koreanMixedMode: "한국어 + English",
    applied: "Applied the aesthetic’s native visual system.",
    randomized: "Created a new compatible combination.",
    undone: "Restored the previous combination.",
    redone: "Restored the next combination.",
    copiedLab: "Lab link copied.",
    copiedReference: "Reference view link copied.",
    copyFallback: "Copy the URL from the address bar to share it.",
    close: "Close options",
    compat: (name: string) => `Only options compatible with ${name} can be selected.`,
    incompatible: (name: string) => `Not compatible with ${name}`,
    unavailable: (name: string) => `This combination is unavailable for ${name}.`,
    evidence: "REFERENCE BASIS",
    evidenceChecked: "Reviewed",
    viewSource: "Open source",
    canvas: "FULL-PAGE LIVE CANVAS",
    presetKicker: "CURATED STARTING POINTS",
    presetTitle: ["Switch the whole page", "in one move."],
    presetIntro: "Every preset applies a coherent visual system to the same Field Notes content. Start here, then adjust one layer at a time in the floating mixer.",
    filters: "Preset filters",
    all: "All",
    searchPresets: "Search presets",
    searchPlaceholder: "Search by style, category, or palette",
    showMore: "Show more presets",
    showing: (visible: number, total: number) => `Showing ${visible} of ${total}`,
    noPresets: "No presets match this search.",
    back: "BACK TO TOP",
    footer: "Mix the system. Experience the page.",
  },
  ko: {
    home: "UI Style Lab 홈",
    tagline: "층위를 설계하고, 전체 페이지에서 확인하세요.",
    pageNav: "페이지 바로가기",
    introKicker: "인터랙티브 UI 레퍼런스",
    title: ["디자인 언어를 조합하고", "전체 시스템을 확인하세요."],
    intro: "서로 호환되는 디자인 층위를 선택하면 같은 UI가 즉시 달라집니다. 영문·한글 서체 조합과 차트부터 내비게이션, 페이지 리듬까지 한 화면에서 비교하세요.",
    introOnly: "서로 호환되는 여덟 개의 층위를 선택하면 같은 UI가 즉시 달라집니다. 한글 서체와 차트부터 내비게이션, 페이지 리듬까지 한 화면에서 비교하세요.",
    explore: "실제 조합 바로 보기",
    agentGuideKicker: "에이전트 탐색 지원",
    agentGuideTitle: "에이전트에게 직접 탐색을 맡기세요.",
    agentGuideBody: "Agent Guide를 전달하면 호환 조합을 찾고 레퍼런스 화면을 열어 근거까지 직접 비교할 수 있습니다. 별도 설치는 필요 없습니다.",
    agentGuideLink: "Agent Guide 열기",
    count: "검증된 조합",
    mixer: "디자인 조합 믹서",
    random: "호환되는 무작위 조합 만들기",
    share: "현재 조합 공유",
    undo: "이전 조합으로 되돌리기",
    redo: "다음 조합 다시 적용하기",
    randomShort: "무작위",
    shareShort: "공유",
    undoShort: "이전",
    redoShort: "다음",
    presetsJump: "프리셋",
    presetsJumpLabel: "추천 프리셋으로 이동",
    canvasJump: "캔버스",
    canvasJumpLabel: "라이브 캔버스로 돌아가기",
    shareTitle: "공유 화면 선택",
    shareIntro: "직접 탐색할 수 있는 전체 실험실 또는 에이전트와 디자인 전달에 적합한 레퍼런스 화면을 공유하세요.",
    labLink: "실험실 링크 복사",
    labLinkNote: "믹서, 프리셋과 선택한 캔버스 포함",
    referenceLink: "레퍼런스 링크 복사",
    referenceLinkNote: "선택한 라이브 캔버스만 표시 · 에이전트 전달용",
    languageMenu: "언어와 콘텐츠 모드",
    englishMode: "English",
    koreanOnlyMode: "한국어 only",
    koreanMixedMode: "한국어 + English",
    applied: "미학 고유의 시각 시스템을 적용했습니다.",
    randomized: "새로운 호환 조합을 만들었습니다.",
    undone: "이전 조합으로 돌아왔습니다.",
    redone: "다음 조합을 다시 적용했습니다.",
    copiedLab: "실험실 링크를 복사했습니다.",
    copiedReference: "레퍼런스 링크를 복사했습니다.",
    copyFallback: "주소창의 URL을 복사해 공유하세요.",
    close: "선택창 닫기",
    compat: (name: string) => `${name}의 시각 문법과 호환되는 옵션만 선택할 수 있습니다.`,
    incompatible: (name: string) => `${name}과 호환되지 않음`,
    unavailable: (name: string) => `${name}에서는 사용할 수 없는 조합입니다.`,
    evidence: "레퍼런스 근거",
    evidenceChecked: "검토일",
    viewSource: "출처 열기",
    canvas: "전체 페이지 라이브 캔버스",
    presetKicker: "추천 시작점",
    presetTitle: ["페이지의 분위기를", "한 번에 전환하세요."],
    presetIntro: "각 프리셋은 같은 Field Notes 콘텐츠에 일관된 시각 시스템을 적용합니다. 선택한 뒤 플로팅 믹서에서 한 층씩 바꿔 보세요.",
    filters: "프리셋 필터",
    all: "전체",
    searchPresets: "프리셋 검색",
    searchPlaceholder: "스타일, 분류 또는 팔레트 검색",
    showMore: "프리셋 더 보기",
    showing: (visible: number, total: number) => `${total}개 중 ${visible}개 표시`,
    noPresets: "검색 조건에 맞는 프리셋이 없습니다.",
    back: "맨 위로",
    footer: "시스템을 조합하고, 페이지에서 경험하세요.",
  },
} as const;

export const presetLabelsEn: Record<string, string> = {
  "glass-bento": "A translucent field journal",
  "neo-brutal": "A forceful independent publication",
  "soft-neumo": "A calm wellness journal",
  "swiss-flat": "A field archive organized by grid",
  "bauhaus-function": "A functional archive built from geometry",
  "deco-night": "A nocturnal edition shaped by symmetry and gold lines",
  "nordic-field": "Pale timber tones with a calm information rhythm",
  "editorial-luxury": "A restrained luxury journal",
  "y2k-chrome": "An optimistic future from the 2000s",
  "cyber-hud": "A neon expedition index",
  "atlassian-work": "Semantic tokens for compact product workflows",
  "atlassian-night": "Dark neutrals with bright brand and status roles",
  "primer-repository": "Compact product UI with subtle borders",
  "primer-night": "GitHub dark canvas with accessible action states",
  "sap-horizon-morning": "A rounded current-generation Fiori shell",
  "sap-horizon-evening": "Low-light surfaces with vibrant foregrounds",
  "sap-horizon-hcb": "A black canvas with explicit white accessibility boundaries",
  "sap-horizon-hcw": "A white canvas with explicit black accessibility boundaries",
  "sap-quartz-light": "Compact Fiori 3 geometry with a navy shell",
  "sap-quartz-dark": "Compact geometry with layered charcoal surfaces",
  "sap-quartz-hcb": "A black high-contrast workspace for Fiori 3",
  "sap-quartz-hcw": "A white high-contrast workspace for Fiori 3",
  "sap-belize-legacy": "A gradient shell with legacy Fiori 2 field grammar",
  "material-you": "Tonal color with rounded components",
  "material-night": "Dark tonal roles with soft elevation",
  "mui-dashboard": "MUI paper, blue primary actions, and compact React component rhythm",
  "mui-dashboard-dark": "MUI dark paper with brighter primary and divider roles",
  "fluent-focus": "Layered focus for adaptive productivity",
  "fluent-night": "Dark aliases with bright focus layers",
  "carbon-operations": "An enterprise dashboard built on the 2x Grid",
  "carbon-night": "Dense operations on Carbon Gray 100",
  "shadcn-neutral": "A white canvas with a composable dashboard",
  "shadcn-night": "Zinc dark with a compact component rhythm",
  "zag-statecharts": "Dark statechart flows from the official Zag showcase",
  "tamagui-adaptive": "Rounded cross-platform rhythm with nested themes",
  "tamagui-night": "A near-black canvas with spectral theme accents",
  "nebular-eva": "Semantic Eva colors for compact enterprise components",
  "nebular-night": "A deep navy basic scale with vivid status hierarchy",
  "memphis-pop": "Playful creative tools",
  "frutiger-gloss": "Nature meets the glossy web",
  "terminal-green": "A phosphor field log",
  "paper-report": "A printed annual report",
  "clay-candy": "A soft, dimensional onboarding",
  "adaptive-feed": "A responsive content stream with productive feedback",
  "supporting-workspace": "Primary work paired with a contextual two-to-one pane",
  "operations-table": "Scannable rows for fast status comparison",
  "guided-wizard": "A sequential task flow focused on one step at a time",
  "spring-canvas": "Rounded token UI with restrained physics response",
  "corporate-clean": "An enterprise UI with a navy rail and white canvas",
  "evergreen-workspace": "Calm operations with an evergreen rail and frost canvas",
  "burgundy-workspace": "A warm service UI with a burgundy rail and pearl canvas",
  "graphite-workspace": "Neutral data operations with a graphite rail and snow canvas",
  "vapor-grid": "A dreamy retro travel page",
  "organic-calm": "Wellness with quiet data",
  "citrus-split": "Energetic commerce",
  "skeuo-utility": "A desktop tool rebuilt with tactile controls",
  "eink-fieldbook": "Field records on low-chroma digital paper",
  "recursive-signal": "A digital field signal animated through variable type axes",
  "kakao-screen-pair": "Role-based Korean typography with separate display and body faces",
};
